# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-18 05:03
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqitem',
            name='body',
            field=tinymce.models.HTMLField(),
        ),
    ]
