# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-03 13:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqitem',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 3, 13, 31, 4, 346926)),
        ),
    ]
