# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-03 17:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_faqitem_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqitem',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 3, 17, 24, 52, 510267)),
        ),
    ]
