# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-16 08:50
from __future__ import unicode_literals

from django.db import migrations
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0003_auto_20170714_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=tinymce.models.HTMLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
