# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-18 06:57
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0004_auto_20170718_0507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
