# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-18 07:19
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0005_auto_20170718_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=tinymce.models.HTMLField(),
        ),
    ]
