# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-10 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20160415_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='kind',
            field=models.CharField(choices=[('email', 'Email'), ('webhook', 'Webhook'),
                                            ('hipchat', 'HipChat'), ('slack', 'Slack'),
                                            ('pd', 'PagerDuty'), ('po', 'Pushover'),
                                            ('victorops', 'VictorOps'), ('pushbullet',
                                                                         'PushBullet')],
                                                                         max_length=20),
        ),
    ]
