# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-05 11:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20170705_1144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='priority',
            old_name='owner',
            new_name='current_check',
        ),
    ]
