# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-10 13:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20170710_1302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkaccess',
            old_name='check_id',
            new_name='check_obj',
        ),
        migrations.RenameField(
            model_name='checkaccess',
            old_name='user_id',
            new_name='user',
        ),
    ]
