# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-10 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20170705_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priority',
            name='enabled',
        ),
        migrations.AlterField(
            model_name='priority',
            name='level',
            field=models.IntegerField(choices=[(1, 'High'), (2, 'Medium'), (3, 'Low'), (0, 'None')]),
        ),
    ]
