# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-11 11:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20170710_0854'),
        ('api', '0027_auto_20170710_1515'),
    ]

    operations = [
    ]
