# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-12 09:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_auto_20170711_1306'),
        ('api', '0031_auto_20170712_0819'),
    ]

    operations = [
    ]
