# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-14 15:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_merge_20170712_0957'),
        ('api', '0032_auto_20170711_1856'),
    ]

    operations = [
    ]
