# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-18 19:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_auto_20170717_2028'),
        ('api', '0027_auto_20170710_1515'),
    ]

    operations = [
    ]
