# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-18 19:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_merge_20170718_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='nag_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name='channel',
            name='kind',
            field=models.CharField(choices=[('email', 'Email'), ('webhook', 'Webhook'), ('hipchat', 'HipChat'), ('slack', 'Slack'), ('pd', 'PagerDuty'), ('po', 'Pushover'), ('victorops', 'VictorOps'), ('pushbullet', 'PushBullet'), ('telegram', 'Telegram')], max_length=20),
        ),
    ]
